
import sys

ifile_path = "generate_isa_name_array_input.txt"
ofile_path = "generate_isa_name_array_output.txt"

inst_list = []
with open(ifile_path, "r") as ifile:
    lines = ifile.readlines()
    allline = " ".join(lines)
    allline = allline.replace("\n", "").replace("\t", "").replace(" ", "")
    inst_list = allline.split(",")

with open(ofile_path, "w") as ofile:
    ofile.write("// This code is generated by %s\n" % sys.argv[0])
    ofile.write("char *InstNameStrs[] = {\n")
    for i in inst_list:
        ofile.write("    (char*) \"%s\", \n" % i)
    ofile.write("};\n")

